[project]
name = "langchain-demo"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=1.4.2",
    "langchain-core>=1.6.3",
    "langchain-deepseek>=1.1.0",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "langchain-openrouter>=0.2.8",
    "langchain-tavily>=0.2.18",
    "langfuse>=4.15.4",
    "pydantic-ai>=2.46.0",
    "pydantic-ai-harness>=0.32.0",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
    "tavily>=1.1.0",
]
